blank_issues_enabled: false
contact_links:
  - name: Questions / support
    url: https://github.com/rob2rhyme/school-management-system/issues
    about: Please open an issue with details and context.
